[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2024"
authors = ["Hamze ghalebi@gmail.com"]
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
log = "0.4"
env_logger = "0.11"

[dev-dependencies]
pretty_assertions = "1.4"
